name: Infracost
description: "Generate cost estimates for changes"
permissions:
  contents: read
  pull-requests: write
inputs:
  api_key:
    description: 'Infracost API key'
    required: true
runs:
  using: "composite"
  steps:
  - name: Setup Infracost
    uses: infracost/actions/setup@v2
    with:
      api-key: ${{ inputs.api_key }}

  - name: Checkout base branch
    uses: actions/checkout@v2
    with:
      ref: '${{ github.event.pull_request.base.ref }}'

  - name: Generate Infracost cost estimate baseline
    shell: bash
    run: |
      infracost breakdown --config-file=.github/infracost.yml \
                          --format=json \
                          --out-file=/tmp/infracost-base.json

  - name: Checkout PR branch
    uses: actions/checkout@v2

  - name: Generate Infracost diff
    shell: bash
    run: |
      infracost diff --config-file=.github/infracost.yml \
                      --format=json \
                      --compare-to=/tmp/infracost-base.json \
                      --out-file=/tmp/infracost.json

  - name: Post Infracost comment
    shell: bash
    run: |
        infracost comment github --path=/tmp/infracost.json \
                                  --repo=$GITHUB_REPOSITORY \
                                  --github-token=${{github.token}} \
                                  --pull-request=${{github.event.pull_request.number}} \
                                  --behavior=update
