name: Release

on:
  push:
    branches:
      - main

jobs:
  apply_org_root:
    name: Terraform Apply / AWS Org Root
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Terraform Apply
      uses: ./.github/actions/terraform-apply
      with:
        workspace: ologist-aws-org-root
        environment: root
        aws_access_key: ${{ secrets.AWS_ORG_ROOT__AWS_ACCESS_KEY }}
        aws_secret_key: ${{ secrets.AWS_ORG_ROOT__AWS_SECRET_KEY }}

  # plan_infra:
  #   name: Terraform Plan / AWS Infra (Global)
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Terraform Plan
  #     uses: ./.github/actions/terraform-plan
  #     with:
  #       account: ${{ secrets.AWS_INFRA__AWS_ACCOUNT_ID}}
  #       workspace: ologist-aws-infra/global
  #       environment: root
  #       aws_access_key: ${{ secrets.AWS_INFRA__AWS_ACCESS_KEY }}
  #       aws_secret_key: ${{ secrets.AWS_INFRA__AWS_SECRET_KEY }}

  # plan_id:
  #   name: Terraform Plan / AWS ID (Global)
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Terraform Plan
  #     uses: ./.github/actions/terraform-plan
  #     with:
  #       account: ${{ secrets.AWS_ID__AWS_ACCOUNT_ID}}
  #       workspace: ologist-aws-id/global
  #       environment: root
  #       aws_access_key: ${{ secrets.AWS_ID__AWS_ACCESS_KEY }}
  #       aws_secret_key: ${{ secrets.AWS_ID__AWS_SECRET_KEY }}

  terraform_infracost:
    name: Cost Estimate
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Infracost
      uses: ./.github/actions/terraform-infracost
      with:
          api_key: ${{ secrets.INFRACOST_API_KEY }}
