name: Review

on:
  pull_request:
    branches:
      - main

jobs:
  terraform_plan:
    name: Terraform Plans
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: AWS Org Root
      uses: ./.github/actions/terraform-plan
      with:
        workspace: ologist-aws-org-root
        environment: root
    - name: AWS Infra (Global)
      uses: ./.github/actions/terraform-plan
      with:
        workspace: ologist-aws-infra/global
        environment: root
    - name: AWS ID (Global)
      uses: ./.github/actions/terraform-plan
      with:
        workspace: ologist-aws-id/global

  terraform_infracost:
    name: Cost Estimate
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Infracost
      uses: ./.github/actions/terraform-infracost
      with:
          api_key: ${{ secrets.INFRACOST_API_KEY }}
